default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres # mudar
  password: alexnunes12 # mudar 
  host: localhost
  port: 5432

development:
  <<: *default
  database: listas_development2


test:
  <<: *default
  database: listas_test2


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: listas_production2
  username: listas
  password: <%= ENV["LISTAS_DATABASE_PASSWORD"] %>
