default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>

development:
  <<: *default
  database: listas_development2


test:
  <<: *default
  database: listas_test2


production:
  <<: *default
  database: listas_production2
 
