default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>


development:
  <<: *default
  database: listas_development2


test:
  <<: *default
  database: listas_test2


production:
  <<: *default
  database: listas_production2
 
