default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  host: localhost
  database: kanban_development
  username: postgres
  password: alexnunes12

 
test:
  <<: *default
  host: localhost
  database: kanban_test
  username: postgres
  password: alexnunes12

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV["PGHOST"] %>
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  port: <%= ENV["PGPORT"] %>
