default: &default
  adapter: postgresql
  encoding: unicode
<<<<<<< HEAD
  username: postgres
  password: alexnunes12
=======
  username: postgres # mudar
  password: 1234 # mudar 
>>>>>>> fff12637e76fc555fc72902db355d3e4f45548e1
  host: localhost
  port: 5432

development:
  <<: *default
  database: listas_development2


test:
  <<: *default
  database: listas_test2


production:
  <<: *default
  database: listas_production2
  username: listas
  password: <%= ENV["LISTAS_DATABASE_PASSWORD"] %>
